version: "3"

services:
  node_app:
    container_name: todos
    build: .
    image: homework/node_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=todos
      - PG_USER=postgres
      - PG_PASSWORD=admin
      - PG_HOST=node_db
    depends_on:
      - node_db
  
  node_db:
    container_name: todos
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}


